---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by like.
--- DateTime: 10/27/22 7:50 PM
---

local M = {}

function M.setup(bqf)

    bqf.setup({
        auto_enable = true,
        preview = {
            win_height = 12,
            win_vheight = 12,
            delay_syntax = 80,
            border_chars = { "┃", "┃", "━", "━", "┏", "┓", "┗", "┛", "█" },
        },

        func_map = {
            vsplit = "",
            ptogglemode = "z,",
            stoggleup = "",
        },

        filter = {
            fzf = {
                action_for = { ["ctrl-s"] = "split" },
                extra_opts = { "--bind", "ctrl-o:toggle-all", "--prompt", "> " },
            },
        },
    })
end

return M